name: Build Release

on:
  release:
    types: [ published, edited ]

jobs:
  buildRelease:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build Release Artifacts
        env:
          TAG: ${{ github.ref_name }}
        run: |
            VERSION=$(echo $TAG | sed -nre 's/^[^0-9]*(([0-9]+\.)*[0-9]+).*/\1/p')
            echo "Build OVAL Version ${VERSION}"
            make OVAL_VERSION=${VERSION}
      - name: Attach Release Artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          TAG: ${{ github.ref_name }}
        run: |
            # SCHEMA_FILES=$(ls oval-schemas/*.xsd)
            # gh release upload $TAG $SCHEMA_FILES --clobber --repo $OWNER/$REPO
            VERSION=$(echo $TAG | sed -nre 's/^[^0-9]*(([0-9]+\.)*[0-9]+).*/\1/p')
            gh release upload $TAG schemas-${VERSION}.zip oval_docs-${VERSION}.zip --clobber --repo $OWNER/$REPO
